TARGET = /bin/dbview
SRC = $(wildcard src/*.c)
OBJ = $(patsubst src/%.c, obj/%.o, $(SRC))

.PHONY: all default clean run dirs

run: default
     ./$(TARGET)

default: dirs $(TARGET)

dirs:
     mkdir -p obj bin

clean:
     rm -f obj/*.o
     rm -f bin/*
     rm -f *.db

$(TARGET): $(OBJ)
     gcc -o $@ $^

obj/%.o: src/%.c
     gcc -c $< -o $@ -Iinclude